# AoC 2020

[[exercises]]
name = "2020_1"
path = "year/2020/2020_1.rs"
mode = "compile"
hint = """ """

[[exercises]]
name = "2020_2"
path = "year/2020/2020_2.rs"
mode = "compile"
hint = """ """

# AoC 2021

[[exercises]]
name = "2021_1"
path = "year/2021/2021_1.rs"
mode = "compile"
hint = """ """

[[exercises]]
name = "2021_2"
path = "year/2021/2021_2.rs"
mode = "compile"
hint = """ """
